# This notebook aims to code the softmax function as follows:

![](figures/figure1.jpg)

* Logit is a function that maps probabilities [0, 1] to [-inf, +inf].

* Softmax is a function that maps [-inf, +inf] to [0, 1] similar as Sigmoid. But Softmax also normalizes the sum of the values(output vector) to be 1.

* In ML the term logit:
        Refers to the vector of raw (non-normalized) predictions that a classification model generates, which is ordinarily then passed to a normalization function. If the model is solving a multi-class classification problem, logits typically become an input to the softmax function. The softmax function then generates a vector of (normalized) probabilities with one value for each possible class.


In [4]:
import numpy as np

In [6]:
def softmax(x):
    """
        Compute softmax values for each sets of scores in x.
        @Return results in same shape as x
    
    """
    return np.exp(x)/np.sum(np.exp(x), axis=0)

In [7]:
# test 1
logits = [3.0, 1.0, 0.2]
print(softmax(logits))

[0.8360188  0.11314284 0.05083836]


In [9]:
# test 2
logits = [1.0, 2.0, 3.0]
print(softmax(logits))

[0.09003057 0.24472847 0.66524096]


In [10]:
# test 3
logits = np.array([
    [1, 2, 3, 6],
    [2, 4, 5, 6],
    [3, 8, 7, 6]])
print(softmax(logits))

[[0.09003057 0.00242826 0.01587624 0.33333333]
 [0.24472847 0.01794253 0.11731043 0.33333333]
 [0.66524096 0.97962921 0.86681333 0.33333333]]


# Now let's do it with tensorflow

In [12]:
import tensorflow as tf

In [31]:
logit_data1 = [1.0, 2.0, 3.0]
logit_data2 = np.array([
    [1, 2, 3, 6],
    [2, 4, 5, 6],
    [3, 8, 7, 6]]).T
logits = tf.placeholder(tf.float32)
softmax_tensor = tf.nn.softmax(logits)
with tf.Session() as sess:
    print(f" dataset 1 (test 2): {sess.run(softmax_tensor, feed_dict = {logits:logit_data})}")
    print(f" dataset 2 (test 3): \n{np.array(sess.run(softmax_tensor, feed_dict = {logits:logit_data2})).T}")

 dataset 1 (test 2): [0.09003057 0.24472848 0.66524094]
 dataset 2 (test 3): 
[[0.09003057 0.00242826 0.01587624 0.33333334]
 [0.24472848 0.01794253 0.11731043 0.33333334]
 [0.66524094 0.9796292  0.86681336 0.33333334]]
